### ISSUE TITLE
Нужно изменить топики в вопросе на карточку вопроса

### ISSUE THREAD

**Issue by 3agoskin** [polinazman/sreda.today#2]
# Как-то так
![IMAGE 2022-06-25 19:31:08](https://user-images.githubusercontent.com/96751690/175782530-ef1fbc01-2885-4a27-a387-24bfce8ae289.jpg)

**Comment by 3agoskin** [comment]
И убрать топики из ответа в странице вопроса

**Comment by polinazman** [comment]
Сделано.
